version: "3.8"
services:
  api-min:
    profiles: ['prod']
    image: ghcr.io/jon-at-github/hello-api:min
    ports:  
      - 8080:8080
    build: .
  api-dev:
    profiles: ['dev']
    image: ghcr.io/jon-at-github/hello-api:dev
    ports: 
    - 8080:8080
    build:
      context: .
      target: dev